### ISSUE TITLE
"Transfer" button for migrating Alby hosted balance does not work 

### ISSUE THREAD

**Issue by MoritzKa** [getAlby/hub#237]
... only "Migrate now" button on the side works.

**Comment by rolznz** [comment]
These do two different things
- The side uses the Alby hosted balance to open a channel
- The card on the node page tries to migrate the hosted balance into one of your existing channels

**Comment by MoritzKa** [comment]
good to know 
cc @stackingsaunter

**Comment by reneaaron** [comment]
With the new "first channel" flow this is probably out of date. Funds will usually be migrated automatically during the opening of your first channel, otherwise you will still have the option to migrate your funds over using the "Transfer" button on the node page. 

Feel free to re-open if I missed anything.
