### ISSUE TITLE
Ensure Alby Hub Wails app cannot be run twice

### ISSUE THREAD

**Issue by rolznz** [getAlby/hub#467]

**Comment by rolznz** [comment]
@reneaaron do you think a check should be implemented on the same device first with some sort of file lock? this would solve the chance a user runs two desktop versions of Alby Hub. For server versions, this would not happen due to failing to use the same port.

For cross-device, it might need to be something on the Alby account

**Comment by reneaaron** [comment]
I was more thinking of a file lock that prevents multiple instances running in the same data dir (which could mess up quite some things iirc)

i was also wondering if that has any implications for the encrypted backups in the account. do we actually know which node id this backup is for? how could a user otherwise know which backup to restore if he has multiple instances running?

**Comment by rolznz** [comment]
Our backup channels event has the hub node ID in it, so this should be ok.

But yeah, there is no file lock at the moment to stop 2 nodes running and using the same data directory.
The problem is if we do not clean up the lock properly (e.g. after some sort of ungraceful shutdown) it could cause the app to never start.

**Comment by rolznz** [comment]
We could implement a file lock just for wails for now - i believe it's only possible here.
