### ISSUE TITLE
Reset password

### ISSUE THREAD

**Issue by stevecastaneda** [getAlby/hub#495]
How do you reset the password to login?

**Comment by rolznz** [comment]
Hi,

There is no password reset because Alby Hub is a self-custodial. No-one can recover the password for you if you forget it.

If you wrote down your seed phrase then you can start a new Alby Hub and import the seed phrase again.

It is best to contact support@getalby.com and we can better help you there.

**Comment by stevecastaneda** [comment]
Thanks.  I'll temporarily manage channels using the Lightning Node app in my umbrel.

**Comment by rolznz** [comment]
Hi, is it connected to your umbrel running LND?

Then you can just reinstall Alby Hub, since Alby Hub does not have a seed in this case.

**Comment by stevecastaneda** [comment]
> Hi, is it connected to your umbrel running LND?
> 
> Then you can just reinstall Alby Hub, since Alby Hub does not have a seed in this case.

Yup!  I actually just tried it and it worked just fine.  Sweet!
