### ISSUE TITLE
Add back button on onboarding pages

### ISSUE THREAD

**Issue by stackingsaunter** [getAlby/hub#499]
![image](https://github.com/user-attachments/assets/a5653e96-509c-47aa-ab6b-beeddde0da66)

**Comment by rolznz** [comment]
@stackingsaunter this was already done by @im-adithya but currently looks like this. Is it ok? I think it works better because it's a consistent part of the navigation (in the header). Putting it in the content will be difficult.

![image](https://github.com/user-attachments/assets/59ce8c50-3c9d-46d8-a345-c6264af01880)

**Comment by stackingsaunter** [comment]
Good, but maybe we can change them to Outline?

![image](https://github.com/user-attachments/assets/4db65bf7-5ae5-4728-820e-50015b6297ab)
