### ISSUE TITLE
Add alert on Create Password pages

### ISSUE THREAD

**Issue by stackingsaunter** [getAlby/hub#500]
![image](https://github.com/user-attachments/assets/e02654a8-b202-4500-81b0-24e42c2eb1e2)

![image](https://github.com/user-attachments/assets/abbb5b7f-f4e7-453f-bbd0-923f5291b322)

**Comment by bumi** [comment]
or maybe when I click on "create password" we get another prompt to confirm that the password was saved and is in the users control

**Comment by rolznz** [comment]
I did it Mutiny-style, and I believe this is much more important on the initial setup rather than when a user changes their password, which already has a double confirmation, and the user in that flow is consciously changing their password.

In case anyone does not like the new version, feel free to re-open this issue

**Comment by stackingsaunter** [comment]
I like your solution
