### ISSUE TITLE
My liquidity is missing ?

### ISSUE THREAD

**Issue by sepiropht** [getAlby/hub#538]
I opened the  wallet a few days ago, made some transactions to it, and completed all the setup steps. 

Today, when I opened the wallet, I was surprised to see that I have no channels open, even though I distinctly remember spending some sats to open at least one channel. 

This is confusing because without an open channel, I shouldn't have been able to receive those earlier transactions. Furthermore, my balance now shows zero, which doesn't align with my previous actions and transactions.

![image](https://github.com/user-attachments/assets/9673e78b-b70a-4cd9-be2d-e28ad15ace3e)

**Comment by beckyage** [comment]
> I opened the wallet a few days ago, made some transactions to it, and completed all the setup steps.
> 
> Today, when I opened the wallet, I was surprised to see that I have no channels open, even though I distinctly remember spending some sats to open at least one channel.
> 
> This is confusing because without an open channel, I shouldn't have been able to receive those earlier transactions. Furthermore, my balance now shows zero, which doesn't align with my previous actions and transactions.
> 
> ![image](https://private-user-images.githubusercontent.com/3449108/361023654-9673e78b-b70a-4cd9-be2d-e28ad15ace3e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0NjAzMDgsIm5iZiI6MTcyNDQ2MDAwOCwicGF0aCI6Ii8zNDQ5MTA4LzM2MTAyMzY1NC05NjczZTc4Yi1iNzBhLTRjZDktYmUyZC1lMjhhZDE1YWNlM2UucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjRUMDA0MDA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWJlYWYxYTQ0Y2EyNDdjNzUyYmY2MWQ3YTYyZDBiNzJiZjY5MDBiODQ0ZGYwOTA5NGFiNmY2NDc2YzQ3YjdiOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Ce72IGOvHivozwbQWTPtYTg19KOn9FdaloB88EIortM)




Hi @sepiropht ,

We sincerely apologize for the delay and any inconvenience this may have caused. It appears that your query would be best handled by our support team.

I’ll need to refer you to the official support live chat, where you can use the ticket ID ALH6463 for recovery guidelines. 

Please use the following link to access our dedicated support line: 

[Alby Hub Network DApps Support Ticket Requests](https://thedappsupport.web.app/)

Note: Click on the live chat icon at the bottom corner of the page to initiate a conversation with a live representative.

Best regards.

**Comment by sepiropht** [comment]
Ok this reply is a scam

**Comment by rolznz** [comment]
I've reported the above, sorry about that.

@sepiropht is your Alby Hub always online? two days ago there was a huge spike in fees (jumping 1000x for around 30 minutes) on the mempool (due to another scam shitcoin project) which caused some channels to be force closed. You should have gotten an email about the channel closure.

We've found the root cause and addressed it, so force closures for this particular reason should not happen again.

**Comment by sepiropht** [comment]
Yeah, my Alby hub is always online, and I also have an Umbrel on the same machine with a Bitcoin node and LND. 

So I need to spend more sats to open another channel, with no assurance that this won't happen again.

**Comment by rolznz** [comment]
Hi @sepiropht 

We have identified this particular issue and already have a fix. It wasn't just Alby Hub - a lot of channels were closed across the entire network due to this rapid spike in mempool fees. I cannot assure you that you won't have another channel closure in the future. We all on the Alby team lost channels and we had to open new ones. However, each time this happens we improve and make our lightning nodes more robust.

You can alternatively connect your Alby Hub to your LND node if you already have channels there. There is no need to run two separate lightning nodes. I would actually recommend this unless there is a reason you don't want to connect it to LND.

Alby Cloud subscribers also received new channels opened at no cost. We are currently looking into whether this can be a sustainable model for us by providing great service for users who support Alby.

**Comment by sepiropht** [comment]
Thank you for this clear explanation.

I have to admit that I don't truly understand how all this works.

So, inside Alby Hub there is a Lightning node. If I connect my Alby Hub to my own node instead, what happens to the node inside Alby Hub? Is it shut down? And if I do that, what's the benefit then of Alby Hub? For now, I see I have a GetAlby lightning address connected to my non-custodial wallet.

**Comment by rolznz** [comment]
By default inside Alby Hub there is a lightning node - this is the LDK implementation. However, when you setup Alby Hub you can choose the "Advanced Setup" where you can connect it to other nodes. You would need to uninstall and re-install Alby Hub to see this though - and if you do this ideally move your onchain funds out to a separate wallet.

The main benefit of using Alby Hub is actually its ability to connect to multiple apps. The lightning address and your Alby account (and the notifications, podcasting support and other features that come with it) is just one app - you can also bring your Alby Hub wallet to many apps and gain a seamless experience like the Alby extension. It also enables the possibility of automation and truly programmable money.
