### ISSUE TITLE
Show seed Words on Phoenixd with Umbrel on GUI

### ISSUE THREAD

**Issue by pizzesser** [getAlby/hub#649]
Hi everyone.

I Run the Alby Hub with Phoenixd on Umbrel. (v.1.8.0)

There is no option in the GUI to show the Seed Words. To show the Seed Words i need to do it in the Umbrel Terminal.
Does this have any reason?
![ALby](https://github.com/user-attachments/assets/636b9154-4f07-40ae-b3fe-acc1a11cdd26)

**Comment by bumi** [comment]
There is no possibility for us to do that. phoenixd is a different tool that exposes an API which is used by Alby Hub. There is no way for Alby Hub to get those seed words. You can only get those through phoenixd. 

Probably because there is no easy way to do this on Umbrel they might also not have official support for umbrel, yet.

**Comment by pizzesser** [comment]
okey thank you!
