### ISSUE TITLE
Documentation for LND backend

### ISSUE THREAD

**Issue by xjmzx** [getAlby/hub#799]
I've installed with the[ install script](https://github.com/getAlby/hub/tree/master/scripts/linux-x86_64) for x86 server with an LND backend. I wasn't sure how configuration workflow follows from the landing page. 

Could anyone highlight the steps required to configure hub to detect LND?
Apologies if this is already answered elsewhere.

**Comment by rolznz** [comment]
Hi @xjmzx when you open Alby Hub, there is a basic and advanced setup. You should choose the advanced setup and then LND, and you will have a form to enter your LND connection details. Does that work for you?

Otherwise you can set the LND environment variables as per the README: https://github.com/getAlby/hub?tab=readme-ov-file#lnd-backend-parameters

**Comment by xjmzx** [comment]
Thanks for that. I'm testing my setup and will continue tomorrow. From following the onboarding flow, errors after inputting gRPC, TLS and admin macaroon hex.

`
rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: tls: failed to verify certificate: x509: certificate signed by unknown authority"
`

I also tried to provide paths for the cert and macaroon in `.env` but seems to have a hard time connecing there too. I could well be doing something wrong in the set up process. 

My chain and graph are synced. 
Are there any other requirements, or any ideas where to look for the problem? Seems similar to #405

Ubuntu x86
lnd version 0.18.3-beta commit=v0.18.3-beta
Bitcoin Core version v27.2.0

**Comment by singlebeam** [comment]
I ran into the same issue on a test server, and I was able to get around it by removing `tlsencryptkey=true` from my `lnd.conf`.  I'm not comfortable using such a configuration in production, so I'm hoping to resolve the issue.  I feel as though the issue lies with albyhub, as other services like ThunderHub don't have any issues with TLS and `tlsencryptkey=true`.

**Comment by xjmzx** [comment]
Thx for pointing me to the docs @rolznz and the ideas for checking lnd's settings @singlebeam 

Have tried with both Let's Encrypt and self-signed certs, but still can't get either to authenticate. Same error as above.

 Like was mentioned above, it seems odd that other ssl services have no problem with self-signed certificate. Would be good if there was more documentation / template  for setting up a reverse-provy and certs for hub.

Unfortunately, `tlsencryptkey=false`  or `tlsencryptkey=true` didn't make any difference either.

**Comment by rolznz** [comment]
@xjmzx sorry you couldn't get it working. There is issue #405 which is probably the same. I wonder if in Alby Hub we can somehow allow self-signed certificates CC @im-adithya
